name: Release Automation

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Specify the .NET version

      # Step 3: Build Project (Framework-Dependent)
      - name: Build Project
        run: dotnet publish -c Release -r win-x64 --self-contained false -o ./dist

      # Step 4: Archive the Build
      - name: Archive Build
        run: zip -j ./dist/release-asset.zip ./dist/*

      # Step 5: List Directory Contents for Debugging
      - name: List Directory Contents
        run: ls -R ./dist

      # Step 6: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Add your release notes here
          draft: false
          prerelease: false

      # Step 7: Upload Release Asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/release-asset.zip
          asset_name: release-asset.zip
          asset_content_type: application/zip
