name: Release Automation

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and archive the asset
      - name: Build Project
        run: dotnet publish -c Release -o ./dist

      - name: Archive Asset
        run: zip -r ./dist/release-asset.zip ./dist/*

      - name: List Directory Contents
        run: ls -R ./dist

      # Step 3: Create a release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        with:
          tag_name: ${{ github.ref_name }} # Use the tag name that triggered the workflow
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Add your release notes here
          draft: false
          prerelease: false

      # Step 4: Upload the release asset
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/release-asset.zip
          asset_name: release-asset.zip
          asset_content_type: application/zip
